# Generated by Django 5.0.6 on 2024-06-29 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone', models.TextField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Blood_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='donardetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True, max_length=40, null=True)),
                ('Phone', models.TextField(max_length=12)),
                ('Blood_type', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=50, null='')),
                ('current_Address', models.CharField(blank=True, max_length=50, null='')),
                ('Drinking', models.BooleanField(default=False)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
                ('Smoking', models.BooleanField(default=False)),
                ('Health_issue', models.CharField(blank=True, max_length=50, null='')),
                ('Full_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
