# Generated by Django 5.0.6 on 2024-07-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donardetail',
            name='Address',
            field=models.TextField(blank=True, max_length=50, null=''),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='Phone',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donardetail',
            name='current_Address',
            field=models.TextField(blank=True, max_length=50, null=''),
        ),
    ]
