# Generated by Django 5.0.6 on 2024-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0002_alter_donardetail_address_alter_donardetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donardetail',
            name='Phone',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
